---
# From First_playbook.yml hello-world example
- name: stopDCgenerate
  hosts: all
  ignore_errors: yes

  tasks:
    
    - name: remove {{ACKSERVER}}
      file:
        path: "{{ACKSERVER}}"
        state: absent

    - name: killall chuck
      shell: killall chuck
    
    - name: FPP and QSERVER > {{ACKSERVER}}
      copy:
        content: FPP {{FPP}} QSERVER {{QSERVER}}
        dest: "{{ACKSERVER}}"

